server:
  port: 8089
  ssl:
    key-store: 3635119_w.bjwinstech.com.pfx
    key-store-password: T6a8WnvU
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.web.cssd_web
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    url: jdbc:mysql://39.98.68.53:3306/w_wechat?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
    #url: jdbc:mysql://localhost:3306/w_wechat?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: sa
    password: Minxin#dev1
  mvc:
    static-path-pattern: /**
  resources:
    #static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:\upload\img\
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/wechat/data/
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.163.com
    username: steris_wechat@163.com
    password: steris1024
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
        prot: 465
pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true